services:
  - type: web
    name: real-time-dashboard
    env: static
    buildCommand: cd Real-Time-Process-Monitoring-Dashboard-main && npm ci && npm run build
    staticPublishPath: Real-Time-Process-Monitoring-Dashboard-main/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
